# Generated by Django 5.1.4 on 2025-01-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('display_order',), 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
